// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdbvtdjkyidvwcbeogxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkYnZ0ZGpreWlkdndjYmVvZ3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTE4ODIsImV4cCI6MjA3MTg2Nzg4Mn0.SQIClX1VXQjwrA0ikSkg3gTDrk4RfKT5a3d_3HxWdaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});